# Generated by Django 4.1.9 on 2023-06-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
