# Generated by Django 4.1.9 on 2023-06-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0002_contact_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="enquiry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="listing.listings",
            ),
        ),
    ]
