# Generated by Django 4.1.9 on 2023-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0003_contact_enquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
