# Generated by Django 4.1.9 on 2023-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0004_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="media",
            field=models.ImageField(upload_to="media"),
        ),
    ]
