# Generated by Django 4.1.9 on 2023-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0005_alter_listings_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="Area",
            field=models.IntegerField(null=True),
        ),
    ]
